# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML
      - id: check-added-large-files
        name: Check for added large files
  # Automatic style formatter for various file types
  # See `.prettierrc.yaml` for configuration
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        name: Prettier
  # Automatic style formatter for Python
  # See the `tool.black` section of `pyproject.toml` for configuration
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black .
        language: system
        pass_filenames: false
  # Python import sorter
  # See `tool.isort` section of `pyproject.toml` for configuration
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        pass_filenames: false
  # Python style guide enforcer
  # See `.flake8` for configuration
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: poetry run flake8
        language: system
        pass_filenames: false
  # Python static type checker
  # See `tool.mypy` section of `pyproject.toml` for configuration
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: poetry run mypy .
        language: system
        pass_filenames: false
